/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color } from "./interface";
export namespace Components {
    interface JzetAvatar {
        /**
          * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`.
         */
        "appearance"?: Color;
        "imgURL"?: string;
        "name": string;
        "size"?: 'small' | 'large';
    }
    interface JzetBadge {
        /**
          * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`.
         */
        "appearance"?: Color;
        "form"?: 'circle' | 'pill';
    }
    interface JzetButton {
        /**
          * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`.
         */
        "appearance"?: Color;
        /**
          * If `true`, the user cannot interact with the button.
         */
        "disabled": boolean;
        /**
          * Set to `"block"` for a full-width button.
         */
        "expand"?: 'default' | 'block';
        /**
          * Set to `"minimal"` for a transparent button, to `"outline"` for a transparent button with a border, or to `"solid"`. The default style is `"solid"`
         */
        "fill"?: 'minimal' | 'outline' | 'solid';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLJzetAvatarElement extends Components.JzetAvatar, HTMLStencilElement {
    }
    var HTMLJzetAvatarElement: {
        prototype: HTMLJzetAvatarElement;
        new (): HTMLJzetAvatarElement;
    };
    interface HTMLJzetBadgeElement extends Components.JzetBadge, HTMLStencilElement {
    }
    var HTMLJzetBadgeElement: {
        prototype: HTMLJzetBadgeElement;
        new (): HTMLJzetBadgeElement;
    };
    interface HTMLJzetButtonElement extends Components.JzetButton, HTMLStencilElement {
    }
    var HTMLJzetButtonElement: {
        prototype: HTMLJzetButtonElement;
        new (): HTMLJzetButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "jzet-avatar": HTMLJzetAvatarElement;
        "jzet-badge": HTMLJzetBadgeElement;
        "jzet-button": HTMLJzetButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JzetAvatar {
        /**
          * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`.
         */
        "appearance"?: Color;
        "imgURL"?: string;
        "name"?: string;
        "size"?: 'small' | 'large';
    }
    interface JzetBadge {
        /**
          * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`.
         */
        "appearance"?: Color;
        "form"?: 'circle' | 'pill';
    }
    interface JzetButton {
        /**
          * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`.
         */
        "appearance"?: Color;
        /**
          * If `true`, the user cannot interact with the button.
         */
        "disabled"?: boolean;
        /**
          * Set to `"block"` for a full-width button.
         */
        "expand"?: 'default' | 'block';
        /**
          * Set to `"minimal"` for a transparent button, to `"outline"` for a transparent button with a border, or to `"solid"`. The default style is `"solid"`
         */
        "fill"?: 'minimal' | 'outline' | 'solid';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "jzet-avatar": JzetAvatar;
        "jzet-badge": JzetBadge;
        "jzet-button": JzetButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jzet-avatar": LocalJSX.JzetAvatar & JSXBase.HTMLAttributes<HTMLJzetAvatarElement>;
            "jzet-badge": LocalJSX.JzetBadge & JSXBase.HTMLAttributes<HTMLJzetBadgeElement>;
            "jzet-button": LocalJSX.JzetButton & JSXBase.HTMLAttributes<HTMLJzetButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
